require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/packagings", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Packaging. As you add validations to Packaging, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { nombre: "Caja de cartón" }
  }

  let(:invalid_attributes) {
    { nombre: "" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Packaging.create! valid_attributes
      get packagings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      packaging = Packaging.create! valid_attributes
      get packaging_url(packaging)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_packaging_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      packaging = Packaging.create! valid_attributes
      get edit_packaging_url(packaging)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Packaging" do
        expect {
          post packagings_url, params: { packaging: valid_attributes }
        }.to change(Packaging, :count).by(1)
      end

      it "redirects to the created packaging" do
        post packagings_url, params: { packaging: valid_attributes }
        expect(response).to redirect_to(packaging_url(Packaging.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Packaging" do
        expect {
          post packagings_url, params: { packaging: invalid_attributes }
        }.to change(Packaging, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post packagings_url, params: { packaging: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { nombre: "Pallet plástico" }
      }

      it "updates the requested packaging" do
        packaging = Packaging.create! valid_attributes
        patch packaging_url(packaging), params: { packaging: new_attributes }
        packaging.reload
        expect(packaging.nombre).to eq("Pallet plástico")
      end

      it "redirects to the packaging" do
        packaging = Packaging.create! valid_attributes
        patch packaging_url(packaging), params: { packaging: new_attributes }
        packaging.reload
        expect(response).to redirect_to(packaging_url(packaging))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        packaging = Packaging.create! valid_attributes
        patch packaging_url(packaging), params: { packaging: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested packaging" do
      packaging = Packaging.create! valid_attributes
      expect {
        delete packaging_url(packaging)
      }.to change(Packaging, :count).by(-1)
    end

    it "redirects to the packagings list" do
      packaging = Packaging.create! valid_attributes
      delete packaging_url(packaging)
      expect(response).to redirect_to(packagings_url)
    end
  end
end
